name:                succinct
version:             0.1.0.0
github:              "annie.cherk/succinct"
license:             BSD3
author:              "Annie Cherkaev"
maintainer:          "annie.cherk@gmail.com"
copyright:           "Beerware"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/annie.cherk/succinct#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- vector
- split
- hw-rankselect-base
- hw-rankselect

library:
  source-dirs: src

executables:
  succinct-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - succinct


tests:
  succinct-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - succinct
